CREATE DATABASE IF NOT EXISTS cisc3003_p2b_dc227126 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cisc3003_p2b_dc227126;
CREATE TABLE IF NOT EXISTS contact_messages(id INT AUTO_INCREMENT PRIMARY KEY,full_name VARCHAR(80) NOT NULL,email VARCHAR(120) NOT NULL,subject VARCHAR(120) NOT NULL,message_body TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
