CREATE DATABASE IF NOT EXISTS cisc3003_p2c_dc227126 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cisc3003_p2c_dc227126;
CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY,full_name VARCHAR(80) NOT NULL,email VARCHAR(120) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,activation_token VARCHAR(64),is_active TINYINT(1) NOT NULL DEFAULT 0,reset_token VARCHAR(64),reset_expires DATETIME,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
